let state={step:0,scan:null,name:'',features:['chat','memory','voice'],config:null,storage:null}; const page=document.getElementById('page');
const labels=['Welcome','System Scan','Hardware Recommendation','Storage','Agent Setup','Features','Review','Finish'];
function render(){let s=state.step; document.getElementById('title').textContent=labels[s]; if(s===0) page.innerHTML='<p>This wizard configures your local AI system. No Docker or YAML knowledge is required.</p><button onclick="next()">Get Started</button>'; if(s===1) page.innerHTML='<p>Detect your computer, GPUs, storage, and available capacity.</p><button onclick="scan()">Scan My System</button>'; if(s===2){let h=state.scan.hardware.hardware,g=state.scan.hardware.gpu_roles; page.innerHTML=`<div class=card>System: ${h.os}<br>CPU: ${h.cpu.model} (${h.cpu.cores} cores)<br>Memory: ${h.ram_gb} GB</div>`+(h.gpus.length?h.gpus.map(x=>`<div class=card>${x.model} — ${x.vram_gb} GB VRAM — ${x.capability}</div>`).join(''):'<div class=card>CPU fallback (no GPU detected)</div>')+`<p class=muted>Recommended primary: ${g.primary_gpu}</p><button onclick="next()">Use Recommended Setup</button>`;} if(s===3){let v=state.scan.storage.find(x=>x.recommended)||state.scan.storage[0]||{}; page.innerHTML=`<div class=card><b>Recommended storage</b><br>${v.path||'Unavailable'}<br>${v.free_gb||0} GB free</div><button onclick="next()">Use Recommended Storage</button>`;} if(s===4) page.innerHTML='<label>Agent name<br><input id=name placeholder="Billy"></label><label>Role<br><input value="Primary Assistant" disabled></label><button onclick="setName()">Continue</button>'; if(s===5) page.innerHTML=['chat','memory','voice','image_generation','video_generation','web_search'].map(f=>`<label><input type=checkbox value=${f} ${state.features.includes(f)?'checked':''}> ${f.replaceAll('_',' ')}</label>`).join('')+'<button onclick="setFeatures()">Continue</button>'; if(s===6) page.innerHTML=`<div class=card>Agent: ${state.name}<br>Features: ${state.features.join(', ')}<br>Storage: ${(state.scan.storage.find(x=>x.recommended)||state.scan.storage[0]||{}).path||'Unavailable'}</div><button onclick="build()">Create Configuration</button>`; if(s===7) page.innerHTML=`<p>${state.name} is configured.</p><p class=muted>Services are not installed in this milestone.</p><div class=card>${state.config?.saved||''}</div>`;}
function next(){state.step++;render()} async function scan(){state.scan=await (await fetch('/api/scan')).json();state.storage=state.scan.storage.find(x=>x.recommended)||state.scan.storage[0];state.step=2;render()} function setName(){state.name=document.getElementById('name').value.trim()||'Assistant';next()} function setFeatures(){state.features=[...document.querySelectorAll('input[type=checkbox]:checked')].map(x=>x.value);next()} async function build(){let p=await (await fetch('/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:state.name,features:state.features,storage:state.storage})})).json();let s=await (await fetch('/api/save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({config:p.config})})).json();state.config={saved:s.path};next()} async function showChat(){page.innerHTML=`<h2>${state.name}</h2><div id=messages class=card></div><input id=chat placeholder="Message ${state.name}"><button onclick="sendChat()">Send</button>`} async function sendChat(){let el=document.getElementById('chat'),box=document.getElementById('messages'),m=el.value.trim();if(!m)return;box.innerHTML+=`<p><b>You:</b> ${m}</p><p id=wait>Waiting…</p>`;el.value='';let r=await fetch('/api/chat_with_agent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({agent:{id:'agent_001',display_name:state.name},message:m})});let d=await r.json();document.getElementById('wait').remove();box.innerHTML+=`<p><b>${state.name}:</b> ${r.ok?d.text:'Your AI service is unavailable.'}</p>`} render();
async function api(path,body){let r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body||{})});return r.json()}
async function showChat(){let cs=await api('/api/conversations',{agent_id:'agent_001'});state.conversation=(cs[0]||{}).id||(await api('/api/conversation',{agent_id:'agent_001'})).id;page.innerHTML=`<h2>${state.name}</h2><button onclick="newConversation()">+ New Conversation</button><button onclick="loadMemories()">Memory</button><div id=conversation-list>${cs.map((c,i)=>`<button onclick="openConversation('${c.id}')">${c.title||'Conversation '+(i+1)}</button>`).join('')}</div><div id=messages class=card></div><input id=chat placeholder="Message ${state.name}"><button onclick="sendChat()">Send</button><div id=memory-panel class=card><b>Memories ${state.name} Keeps</b><p class=muted>Memories are details ${state.name} can use in future conversations.</p><div id=memories></div><input id=memory placeholder="Add a memory"><button onclick="addMemory()">Save Memory</button></div>`;openConversation(state.conversation);loadMemories()}
async function newConversation(){state.conversation=(await api('/api/conversation',{agent_id:'agent_001'})).id;document.getElementById('messages').innerHTML=''}
async function openConversation(id){state.conversation=id;let r=await api('/api/conversation/get',{id,agent_id:'agent_001'});document.getElementById('messages').innerHTML=(r.messages||[]).map(x=>`<p><b>${x.role}:</b> ${x.content}</p>`).join('')}
async function loadMemories(){let r=await api('/api/memories',{agent_id:'agent_001'});let e=document.getElementById('memories');if(e)e.innerHTML=(r||[]).map(x=>`<p>${x.content} <button onclick="delMemory(${x.id})">Delete</button></p>`).join('')||'<p>None stored.</p>'}
async function addMemory(){let e=document.getElementById('memory');if(e.value.trim())await api('/api/memory',{agent_id:'agent_001',content:e.value.trim()});e.value='';loadMemories()}
async function delMemory(id){await api('/api/memory/delete',{agent_id:'agent_001',id});loadMemories()}
async function speak(text){let r=await fetch('/api/synthesize_agent_speech',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({agent:{id:'agent_001',display_name:state.name,voice_id:'voice_001'},text})});if(!r.ok){alert('Voice unavailable');return}let d=await r.json();let a=new Audio('data:audio/wav;base64,'+d.audio_base64);a.play()}
